---
title: My Personal Life
description: What's going on in my life
twitter_username: amy_tmi
disqus_shortname: amy-mac
url: http://amy-mac.com

owner:
  name: Amy MacKinnon
  email: amy@amy-mac.com

# Where things are
category_dir: "life/categories"
include: [".htaccess", "images"]
exclude: ["_drafts", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "README.md", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files: [".git", ".svn"]
show_drafts: null
unpublished: false
timezone: America/Los_Angeles

sass:
  sass_dir: /assets/css/
  style: :compressed

encoding:            "utf-8"
# Conversion
markdown:    kramdown
markdown_ext:        "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false
permalink: /life/:year/:month/:title/
strict_front_matter: false

paginate_path: "/life/page:num"
paginate: 10

plugins:
- jekyll-paginate
- jekyll-category-pages

# Markdown Processors
kramdown:
  auto_ids:      true
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  input:         GFM
  hard_wrap:     false
  footnote_nr:   1
  show_warnings: false

defaults:
-
  scope:
    path: "/life"
    type: "posts"
  values:
    author: "amy@amy-mac.com"
    comments: true
