title: My Personal Life
description: What's going on in my life
disqus_shortname: amy-mac
url:         http://amy-mac.com

owner:
  name: Amy MacKinnon
  email: amy@amy-mac.com

# include: ['images']
exclude: [_drafts]
show_drafts: nil
timezone: America/Los_Angeles

permalink: /life/:year/:month/:title/
category_dir: "/life/categories"
markdown: redcarpet
redcarpet:
  extensions:
    - smart
pygments: true

paginate_path: "/life/page:num"
paginate: 10
