title: My Blog
description: Mostly about tech stuff
disqus_shortname: amy-mac
url: http://amy-mac.com

owner:
  name: Amy MacKinnon
  email: amy@amy-mac.com

include: ['images']
exclude: [_drafts]
show_drafts: nil
timezone: America/Los_Angeles

permalink: /blog/:year/:month/:title/
category_dir: "blog/categories"
markdown: redcarpet
redcarpet:
  extensions:
    - smart
pygments: true

paginate_path: "blog/page:num"
paginate: 10

sass:
  style:  expanded  # nested|expanded|compact|compressed
  deploy_style: compressed  # nested|expanded|compact|compressed
  # "deploy_style:" is used only for building the site
  # (ie: not using the --watch flag)

  compile_in_place: false   # true|false
  # If true, compiles sass directly into your jekyll source directory
  # As well as your destination directory