title: My Blog
description: Mostly about tech stuff
disqus_shortname: amy-mac
url: http://amy-mac.com

owner:
  name: Amy MacKinnon
  email: amy@amy-mac.com

include: ['images']
show_drafts: nil
timezone: America/Los_Angeles

permalink: /blog/:year/:month/:title/
markdown: redcarpet
redcarpet:
  extensions:
    - smart
pygments: true

paginate_path: "blog/page:num"
paginate: 10