title: My Blog
description: Mostly about tech stuff
disqus_shortname: amy-mac
url: http://localhost:4000

owner:
  name: Amy MacKinnon
  email: amy@amy-mac.com

include: ['images']
exclude:['_drafts']
show_drafts: nil
timezone: America/Los_Angeles

permalink: /blog/:year/:month/:title/
markdown: redcarpet
redcarpet:
  extensions:
    - smart
pygments: true

paginate: 10