---
title: My Blog
description: Mostly about tech stuff

twitter_username: ThatAmyMac
disqus_shortname: amy-mac
url: http://amy-mac.com

owner:
  name: Amy MacKinnon
  email: amy@amy-mac.com

# Where things are
category_dir: "blog/categories"
# collections:
#   posts:
#   output:   true
#   permalink: /blog/:year/:month/:title/
sass:
  sass_dir: /assets/css/
  style: :compressed

# Handling Reading
include:             [".htaccess", "images"]
exclude:             ["Gemfile", "Gemfile.lock", "life", "node_modules", "Rakefile", "README.md", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files:          [".git", ".svn"]
encoding:            "utf-8"
markdown_ext:        "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Filtering Content
show_drafts: null
# limit_posts: 0
unpublished: false

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Outputting
permalink: /blog/:year/:month/:title/
paginate_path: "/blog/page:num"
paginate: 10
timezone: America/Los_Angeles

plugins:
- jekyll-paginate
- jekyll-category-pages
- jekyll-feed

# Markdown Processors
kramdown:
  auto_ids:      true
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  input:         GFM
  hard_wrap:     false
  footnote_nr:   1
  show_warnings: false

defaults:
-
  scope:
    path: "/blog"
    type: "posts"
  values:
    author: "amy@amy-mac.com"
    comments: true
