---
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: layout
  label: Layout
  type: text
  hidden: false
  default: Post
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
  config:
    date_format: YYYY/MM/DD
    required: true
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: ''
- name: comments
  label: Comments
  type: boolean
  hidden: false
  default: true
- name: share
  label: Share
  type: boolean
  hidden: false
  default: true
- name: author
  label: Author
  type: text
  hidden: false
  default: amy@amy-mac.com
